#Multics Camera Server Configuration
#Sat Nov 08 18:03:47 KST 2025
camera.autoStart=false
camera.frameRate=30
camera.index=0
camera.jpegQuality=0.75
log.level=INFO
server.autoStart=true
server.host=test.example.com
server.port=8080
snapshots.path=images
ui.video.height=480
ui.video.width=640
ui.window.height=768
ui.window.width=1024
